////
This file is intended to be read in HTML via translation with asciidoc.
////

= IronBee Development
:toc2:

== Source Code Repository

IronBee code is availalbe via a git source code repository from git-hub. The
latest source is always available from here as are all releases.

----
https://github.com/ironbee/ironbee
----

To get started with github, please see https://help.github.com.  However, below are
basic instructions to get you started...

Get the code:

----
git clone git://github.com/ironbee/ironbee.git
----

Change to the repo directory:

----
cd ironbee
----

Set your name/email:

----
git config user.name "Your Name"
git config user.email "email@your.dom.ain"
----

Keep the code up-to-date:

----
git checkout master
git pull --rebase
----

Make a local branch for your work:

----
git checkout -b mywork
----

NOTE: You can now commit your changes to your local branch.

Keep your local branch up-to-date with changes upstream:

----
git checkout master
git pull --rebase
git checkout mywork
git rebase master
----

NOTE: Do NOT rebase a branch that is remotly tracked - use merge instead.

Generate a patch:

----
git format-patch origin/master
----

== LuaJIT Code

LuaJIT is currently distributed with IronBee as it is not widely available.  The source is in libs/luajit-2.0-ironbee and is included using git-subtree with full history to allow the tree to later be removed.  The tree is a fork of the upstream LuaJIT with minor build changes. Currently 2.0.1 is tracked.

To update the LuaJIT source, you will need a git with subtree support.  You will need to add the remote:

----
git remote add luajit-2.0 http://luajit.org/git/luajit-2.0.git
----

Then you can merge in the upstream source with:

----
git subtree pull --squash --prefix=libs/luajit-2.0-ironbee luajit-2.0
----

== LibHTP Code

LibHTP is currently distributed with IronBee as it is not widely available.  The source is in libs/libhtp and is included using git-subtree with full history to allow the tree to later be removed.  Currently 0.5 is tracked.

To update the LibHTP source, you will need a git with subtree support.  You will need to add the remote:

----
git remote add libhtp git@github.com:ironbee/libhtp.git
----

Then you can merge in the upstream source with:

----
git subtree pull --squash --prefix=libs/libhtp libhtp 0.5.x
----

== LibInjection Code

The libinjection code is currently distributed with IronBee as it is not widely available.  The source is in libs/libinjection and is included using git-subtree with full history to allow the tree to later be removed.

To update the libinjection source, you will need a git with subtree support.  You will need to add the remote:

----
git remote add libinjection git://github.com/client9/libinjection.git
----

Then you can merge in the upstream source with:

----
git subtree pull --squash --prefix=libs/libinjection libinjection master
----

== StringEncoders Code

The stringencoders code is currently distributed with IronBee as it is not widely available.  The source is in libs/stringencoders taken from:

https://code.google.com/p/stringencoders/downloads/

The version used is: stringencoders-v3.10.3.tar.gz

Considerable modification was done to the build system, but no other major changes were made.

== Coding Style

Please read and understand the coding style from the guide, https://github.com/ironbee/ironbee/blob/master/CODESTYLE.adoc

Realize that any code submitted MUST abide by this guide or it will be rejected.


== Contributing

To contribute code to the project, you will need to be using git to format patches which you can email to the team.

1. Make a local topic branch

	git checkout -b fix-bug-1234

2. Make changes to code and commit locally as many times as needed.
+
----
# Make some changes
vi libs/qi/engine.c

# Add the changes to the index
git add libs/qi/engine.c

# Add some new files to the index
git add modules/mymodule.c

# Check the status of your local repo
git status

# Show a diff of your changes
git diff

# Commit your changes locally. If fixing a bug, then add the issue
# number to the commit message like this:
#  [#1234] Fixed foo by doing bar.
git commit

# Check the log to make sure it is correct
git log
----

3. Use +git-format-patch+ to generate a set of patches and send upstream to be approved/applied.  See also +git-send-email+ and +git-imap-send+ to make this easier.

	* The following would produce a patch file for each commit:

		git format-patch -M origin/master

4. Approver will save the email/patches and use +git am < patch+ to apply, review, test, signoff and commit on your behalf.

	* All commits maintain the original author's name, so you will get recognition for your work.


== Ongoing Contributions

If you or your group will have ongoing contributions, then you should consider using Github's ``fork'' feature instead of sending in patches. This forks a  working copy of the primary IronBee git repository for your own use which you can commit to as you wish. In addition, others can pull, test and contribute to your code as well. Periodically you will want to sync up with the upstream repository and Github allows this through ``Pull Requests''. Below are some  basic instructions for doing this.

1) Create a forked repository in Github

   * Login to your github account
   * Browse to https://github.com/ironbee/ironbee/
   * Click the ``Fork'' button
   * This creates a ``master'' branch

2) Clone the repository locally and setup for collaboration

   * Clone (using your private URI):

		git clone git@github.com:YOURACCOUNT/ironbee.git

   * You now have the ``origin'' pointing at your own repo's ``master'' branch.

   * Add the originating repository URI (the public one) as the ``upstream'' repo:

         git remote add upstream git://github.com/ironbee/ironbee.git
         git fetch upstream

   * This ``upstream'' remote is then used to sync upstream changes or see what has changed.

3) Now you can use this as the repository, commiting whenever you wish.

  * Make some changes locally, commit locally, make more changes, etc.
  * Push your local changes to github:

        git push origin master

4) And fetch changes from upstream when you want.

  * Keep track of Github's ``Fork Queue'', which will list all changes upstream and allow you to apply them to your fork.

  * Manually see what has changed upstream:

        git diff HEAD..upstream/master

  * Manually fetch/merge when an upstream change occurs which you need.

        git fetch upstream
        git diff HEAD..FETCH_HEAD
        git merge upstream/master

    Or just do it all at once with:

        git pull upstream/master

5) When you have your changes working and tested, send a pull request to the upstream repository so that we can merge in your changes to the official repository.

    http://help.github.com/pull-requests/
