Lua / LuaJIT use in IronBee
===========================
Sam Baskinger <sbaskinger@qualys.com>
2015-10-26
:toc: left
:toclevels: 6

Introduction
------------

IronBee Lua support is split into two locations and handles multiple concerns. The approach of this guide is to look first at the services provided by the +ibmod_lua+ IronBee module and then examine those features that are build on top of +ibmod_lua+.

For documentation about how to use the http://www.ironbee.com/docs/devexternal/_lua_a_p_i.html[Lua API], see the Doxygen documentation for IronBee.

Coding Conventions
------------------

This is a collection of tactics that should be used in the Lua code base to aid in clarity. Also are noted some anti-conventions to warn the reader.

- The variable +M+ means "the module we are building and will return at the end of this file."
- Fields prefixed with +ib_+ such as +ib_engine+ are C pointers. For many IronBee structs there is a Lua wrapper (see +engine.lua+ as an example) but the raw C pointer is often required for the FFI.
- There is inconsistency in defining functions.
+
[source,lua]
----
-- These both show up and are the same. The latter is preferred.
local f = function(foo) ... end
local function f(foo) ... end

-- These all show up but are the same. The latter is preferred.
M.f = function(self, foo) ... end
function M.f(self,foo) ... end
function M:f(foo) ... end
----
- There is a bias to put logic in Lua. There are some things that could be done in the C code base or the Lua code base. Typically the preference is to have Lua do the work and for the C code base to be very predictable.


+ibmod_lua+
-----------

The Lua IronBee module tries to separate broad concerns into several files.

+lua_runtime.c+:: How IronBee gets, initializes, and destroys +lua_State+ (or Lua states).
+lua_common.c+:: Given an +ib_engine_t+ and a +lua_State+ this defines some common actions done often in Lua, logging the results through the IronBee engine.
+lua_modules.c+:: Support for defining an IronBee Module in Lua.
+lua_rules.c+:: Supports for defining an external rule in Lua.

Lua Runtime - +lua_runtime.c+
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

LuaJIT is how IronBee accesses Lua (and how Lua, in turn, accesses IronBee). LuaJIT cannot operate on the same +lua_State+ concurrently. Even if a second thread is created using +lua_newthread(L)+ the new thread and the existing thread must execute serially. Doing otherwise results in crashes. This means that +lua_runtime.c+ must concern itself with managing many Lua states.

Care must therefore be taken because different transactions and
different event handlers in the same transaction my get different
Lua states. Do not read values you did not write to the Lua
environment. Do not read values written in different phases.
There is no guarantee that you are executing in the same environment.

Lua states also have a maximum lifetime. That is, after a predetermined number of uses (defined by +MAX_LUA_STACK_USES+ in +lua_runtime.c+) the resource pool will destroy the Lua state and create a new one. This cleans up any floating global values the user did not clean up, either because of a programming error or because another component of IronBee terminated the transaction before the user's code could clean itself up. This does require IronBee to know how to rebuild Lua States after configuration time.

Reloading Lua States
^^^^^^^^^^^^^^^^^^^^

Creating identical Lua states for parallelism and destroying and
creating old Lua states carries with it some unexpected
complexity. Lua Modules can add directives and register
event handlers with the IronBee engine. If, when creating
a new Lua state, we took the same steps to initialize
the Lua module as we did during configuration time, we would
see redefined configuration directives, duplicate modules
registered in the Engine, and duplicate event handlers.

The Lua module must distinguish between initial config-time loading
of a Lua module and a runtime initialization of a Lua state
with a module that has already been loaded with respect to the
IronBee engine.

In +lua_runtime.c+ the function +lua_pool_create_fn()+ is given to the resource pool to tell it how to construct a new Lua state. It will only reload the Main IronBee context as it could be that none of the other contexts are used. The static function +modlua_reload_ctx()+ is called once with the Main context. It iterates through all the +modlua_reload_t+ items stores for that context and reloads them.

At the time of this writing the only interesting reload code is for IronBee modules written in lua. The major difference is that at configuration time the Lua function +load_module()+ found in +module.lua+ is called with the formal parameter +cregister_directive+ set. When +load_module()+ is called after configuration time the +cregister_directive+ parameter is nil and so no C registration of the module or its configuration structure is done, but it is read *from* the IronBee engine.

Lua Modules
------------

IronBee modules written in Lua are defined in +lua_modules.c+. They offer some of the more interesting execution scenarios because program control starts in IronBee, then Lua code defined in a module is called, and from there more C code is called through LuaJIT's Foreign Function Interface (FFI). As a result, even when executing in Lua there are a lot of C pointers and structs. The maintainer of this code base must keep one foot in each paradigm.

Module Configuration
~~~~~~~~~~~~~~~~~~~~

Modules written in Lua dynamically create a C-struct, allocate a copy of it out of a memory manager, and store it in the IronBee context configuration slot available for that IronBee module. In +module.lua+ the function +declare_config()+ allows the user to create a configuration C-struct that contains numbers, strings, and a +void*+ pointer. The name of the C-struct will be +ib_luamod_<idx>_config_t+ where +<idx>+ is the index of the IronBee module in the IronBee engine.

Calls to +get_config()+ (also defined in +module.lua+) will fetch a +void*+ pointer stored in the IronBee context for the users's module and cast it to the generated C-struct type. This allows the user of access members of the C-struct similar to how they would access members of a Lua table.

Module Lifecycle
~~~~~~~~~~~~~~~~

Lua Modules cross the boundary from C into Lua and then back to C. As such they have a particularly complex life cycle. We detail that here.

Phase 1 of 3 - C
^^^^^^^^^^^^^^^^^

.Register A Dynamic Module
This is how a Lua Module starts in an IronBee engine. No Lua parsing
or execution is done _yet_ but just C structures are set up.

First some callback data is initialized. Specifically a
+modlua_luamod_init_t+ structure is given the file to load,
the module name, and a reference to a +modlua_cfg_t+ object
that contains the single Lua stack used for configuration.

Note that during IronBee runtime many Lua stacks are constructed and
initialized identically to support heavy concurrency, but at configuration
time a single stack is used. This stack will be destroyed and rebuilt
after IronBee's configuration phase is over.

Once the callback data is initialized a dynamic module
structure is created with the macro +IB_MODULE_INIT_DYNAMIC()+
and that module is registered with IronBee. The registration
call causes the init function +modlua_luamod_init()+ to be
called with the callback data we've constructed. If that function
does not report an error, the module has loaded successfully.

.Lua Module Init
We just mentioned +modlua_luamod_init()+. Let's unpack what it's doing.

It is a short function that has 3 important steps.

1. Load the Lua Module source code onto the Lua execution stack
   as a function so it can be called. This is where
   file permissions and parse errors occur. This
   loads the Lua code and evaluates it.
2. If step 1 succeeds, the next step is to record module reload
   information. We've mentioned that config time uses a single Lua
   stack but runtime uses many identical Lua stacks.
   This reload setup step makes creating runtime Lua stacks
   possible. Reloading a Lua module prevents
   configuration directives and other engine-modifying
   activities from being executed.
3. Finally the module callbacks are wired. A C or C++ IronBee
   module registers callbacks for the IronBee engine to call
   when control is being passed to the module. The engine
   doesn't know about Lua so this step registers C functions
   with the engine that know how to proxy control to a Lua
   execution stack which in turn will run the module code.

Phase 2 of 3 - Lua Loads
^^^^^^^^^^^^^^^^^^^^^^^^

When a Lua Module actually loads, what happens?

The C code calls the Lua function +modlua.load_module+ which is
defined in the file link:ironbee/module.lua[module.lua].
The +load_module+ function takes these arguments

1. The IronBee engine.
2. The dynamic module created for this Lua module.
3. The name of the module.
4. The index of the module. This is the index in the engine's
   array of loaded modules. It is unique per-runtime, but
   if you have a very stable set of modules you are loading
   this number may often just happen to always be the same.
   Do not rely on this apparent stability, though.
5. A pointer to the C function +modlua_config_register_directive()+
   which is how the loading Lua module can register directives
   with the engine.
6. The user's Lua module file (+mymodule.lua+) loaded as a function.

The +load_module+ function then creates a new Lua module object
and calls the user's loaded Lua file with the that single argument.

This is how the Lua module writer gets the value +local module = ...+.

The module writer can use this object passed to their Lua module code
as documented:

[source,lua]
------------------------------------------------
local module = ...
module:logInfo("Loading module.")

-- Register a event handler.
module:conn_opened_state(function(ib, event)
    ib:logInfo("Firing event %s.", tostring(event))
    return 0
end)

-- Register a directive.
module:register_param1_directive(
    "MyDirective",
    function(module, context, name, param1)
        module:logInfo("Directive %s fired with param %s.", name, param1)
    end
)

module:logInfo("Done loading module.")

return 0
------------------------------------------------

Directive Callbacks
+++++++++++++++++++

Notice in the above code that the user registers a directive.
That function first records the user's Lua function that implements
the directive under the given directive name and type. The C
pointer passed into +load_module()+ is then called with the
module, the directive name, and its type.

Using that information, it registers another C function with the
IronBee engine. The callback just registered will be specific to the
directive type (+PARAM1+, or +ON_OFF+ etc) and is giving just
enough callback information so that the user's original function
can be looked up.

The C callbacks don't even do the looking up of the function.
Every C callback marshals the C callback data and hands it off
to a Lua callback function that looks up the user's module
by index number, then looks up the directive handler by name,
and finally dispatches the directive handler with the
given arguments.

Looking up of the module by the Lua callback function is
accomplished by consulting the file-scoped tables +lua_modules+
and +lua_modules_by_name+. The C callbacks can only indirectly
reference these tables by calling Lua functions defined in
+module.lua+ to protect the tables from accidental corruption
by the C code or by another well-meaning hunk of Lua code.

Event Callbacks
+++++++++++++++

Notice also that, in the above code, a +conn_opened_state+ event handler
is registered. When the Engine opens a connection this will fire.
Unlike directives, which immediately fire a C callback to register
a directive handler, module event callbacks are handled in the
next phase, after the module has finished loading. This is because a Lua
module may register many handlers for the same event but only a single
C callback will be registered to handle them. A directive may only ever have a single callback, so it is immediately registered so the engine can detect directive redefinition errors.

Phase 3 of 3 - C again: wiring callbacks
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

When the Lua module completes its configuration execution
(registering directives, defining callbacks, etc) the last
step is to register a C callback function for every event that
the module has an event handler defined for.

Similarly to directives are handles the C code will ask
a Lua module function if a handler is defined. This is done by
calling the C function +modlua_has_callback()+ which in turn
calls the lua function +get_callbacks()+. The function +get_callbacks()+
will push the list of all handlers for the requested event onto the Lua
stack. The C function +module_has_callback()+ reports if the push
was successful or not.

If the push was successful then a C event handler (aka a callback) is
registered for the module with IronBee. The job if these
callbacks is to acquire a Lua stack if one is not already available for
the running transaction using +modlua_acquirestate()+
and then setup a call to the lua Function +dispatch_module()+.

+dispatch_module()+
+++++++++++++++++++

The Lua function +dispatch_module()+, defined in +module.lua+ is
the entry point of IronBee's ibmod_lua module into a user's Lua
module. There is a lot of code supporting this call, but when a Lua module
starts to handle an event, it starts the Lua execution in this function.

The first task is to marshal all arguments to the user's callback functions. This involves casting C pointers so that LuaJIT knows what
types they are. Then the list of +handlers+ passed into +dispatch_module()+ are each called, in order, on the data provided
from IronBee. If any of these handlers returns non-+IB_OK+ (non-zero)
processing does not stop for the module. It continues. If the user forgets
to return any value from their handler the caller will get +nil+
as the result which will fail the check that +rc == IB_OK+ and an error
will be reported.

That is, from start to finished, how a Lua module executes.

Lua Actions and Operators
-------------------------

These features are documented here, but briefly because we may wish to remove them.

It is possible to create actions that call Lua code. See +action()+ in +engine.lua+. This will construct a Lua function which, when called with a +ib_rule_exec_t+ pointer, will execute a rule action. If called with the parameter set to nil (or with no parameters) the action instance is destroyed.

Also in +engine.lua+ are two functions to create an operator and a stream operator.
The function returned by these calls takes an +ib_tx_t+ pointer and an +ib_field_t+.
If called with tx set to nil or with no arguments the operator instance is destroyed.

Lua Predicate
-------------

Predicate has a set of Lua wrappers intended to make working in predicate in Lua more easy. It has its own link:../predicate/lua_frontend.html[usage documentation].

A maintainer should be aware that any new operator created in the predicate package of IronBee needs to have a corresponding entry made in the table +calls+ of +predicate.lua+. Each entry is a two-element list where the first element is the predicate operator name and the second element describes the number of parameters expected.

Lua Configuration DSL
---------------------

As of IronBee 0.14.0 Lua can fully configure an IronBee engine programatically. This code is in +config.lua+. Before the configuration DSL +config.lua+ was only concerned with setting up an environment to evaluate Waggle functions, which would create rules. Predicate still uses Waggle to express rule structures to IronBee, so Waggle is still used, but it is no longer the only concern of +config.lua+.

And example of the Lua configuration DSL starts with IronBee having a configuration file:

.LuaInclude
----------------------------------------------------------
LoadModule ibmod_lua
LuaInclude "/etc/ironbee/config.lua"
----------------------------------------------------------

The +config.lua+ file would then be evaluated with the
Lua DSL configured and would configure IronBee. An example file
might look like this.

.Lua Configuration Example
[source,lua]
----------------------------------------------------------
InitVar("MY_VAR", "some string")

Site('www.foo.com') {
  SiteId('006d6c58-5286-11e4-88e4-58b035fe7204'),
  Hostname('*'),
  Service('*:*'),
  RuleEnable('id:my_rule'),
  Location('/foo') {
    RuleEnable('id:my_location_rule')
  }
}
----------------------------------------------------------

The above example shows calling the directive +InitVar+
but also how to configure a +Site+ context. There are
3 ways for a site context to be configured. The shown one uses a
table of values. You can also pass a string constant or
use a closure. See the link:http://www.ironbee.com/docs/devexternal/_lua_a_p_i.html#LuaConfiguration[Lua DLS Doxygen]
documentation for more details an examples.

Execution of the configuration DLS starts with defining +gconfig_mt.\__index+. The +gconfig_mt+ is the Global Config Meta Table and is set to +_G+ before evaluating a configuration Lua file. If a symbol cannot be found directly in the global table it is passed to this +__index+ function of +_G+, which is, at evaluation time point to +gconfig_mt+. The +__index+ function determines if a directive exists for the unknown symbol. If it does, that directive is looked up and called with the given parameters. Special processing exists for those directives that designate blocks.


