#! /usr/bin/env python
"""
 * Licensed to Qualys, Inc. (QUALYS) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * QUALYS licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
"""

"""
This is a Python program to wrap the IronBee command line client.
This program has the ability to read text files with a list of IP
addresses/host names or user agents, and to invoke the cli with arguments for
each of those listed.  Additionally, it provides a cleaner and easier to use
command line; the main cli is encumbered by C and getopt_long().
"""
import sys
import os
import re
import socket
import copy
from subprocess import *
from optparse import OptionParser

class Main( object ) :
    """ Main class, does all of the real work """

    def __init__( self ) :
        """ Class initializer; creates the OptionParser object """
        self._parser = OptionParser(
            usage="usage: %prog <config> <req> <resp> [options]",
            version="%prog 0.1" )

    def InitParser( self ) :
        """ Initialize the command line parser. """
        self._parser.set_defaults( agent_file = None )
        self._parser.add_option( "--agent-file",
                                 action="store", dest="agent_file",
                                 help="Specify file of user agent strings" )
        self._parser.set_defaults( rip_file = None )
        self._parser.add_option( "--remote-ip-file",
                                 action="store", dest="rip_file",
                                 help="Specify remote IP address file" )

        self._parser.set_defaults( cli_options = [] )
        def CliCallback(option, opt, value, parser):
            parser.values.cli_options += value.split(";")
        self._parser.add_option( "--cli",
                                 action="callback", callback=CliCallback,
                                 nargs=1, type="string",
                                 help="Specify CLI options (';' separated)" )
        def DumpCallback(option, opt, value, parser):
            for v in value.split(",") :
                parser.values.cli_options += ["--dump", v];
        self._parser.add_option( "--dump",
                                 action="callback", callback=DumpCallback,
                                 nargs=1, type="string",
                                 help="Specify fields to dump (',' separated)" )
        def ReqHdrCallback(option, opt, value, parser):
            parser.values.cli_options += ["--request-header", value];
        self._parser.add_option( "--rh", "--request-header",
                                 action="callback", callback=ReqHdrCallback,
                                 nargs=1, type="string",
                                 help="Specify a request header field" )


        self._parser.set_defaults( out = None )
        self._parser.add_option( "-o", "--output",
                                 action="store", dest="out",
                                 help="Specify output file" )

        self._parser.set_defaults( execute = True )
        self._parser.add_option( "--execute",
                                 action="store_true", dest="execute",
                                 help="Enable execution <default>" )
        self._parser.add_option( "-n", "--no-execute",
                                 action="store_false", dest="execute",
                                 help="Disable execution (for test/debug)" )
        self._parser.set_defaults( verbose = 0 )
        self._parser.add_option( "-v", "--verbose",
                                 action="count", dest="verbose",
                                 help="Increment verbosity level" )
        self._parser.set_defaults( quiet=False )
        self._parser.add_option( "-q", "--quiet",
                                 action="store_true", dest="quiet",
                                 help="Be vewwy quiet (I'm hunting wabbits)" )

    def Parse( self ) :
        """ Parse the command line. """
        (self._opt, self._args) = self._parser.parse_args()
        if len(self._args) != 3 :
            self._parser.error( "Missing args" )
        if ( self._opt.agent_file is not None and
             self._opt.rip_file is not None ) :
            self._parser.error(
                "Both user agent file and remote address file specified")
        self._config = self._args[0]
        self._req = self._args[1]
        self._resp = self._args[2]

    def InitCommand( self ) :
        """ Initialize the base cli command. """
        cli = os.path.join( os.path.dirname(sys.argv[0]), "ibcli" )
        self._cmd = [ cli,
                      "--config", self._config,
                      "--request-file", self._req,
                      "--response-file", self._resp,
                      ]
        self._cmd += self._opt.cli_options

    def RunCli( self, args=None ) :
        """ Run the cli, using self._cmd as the base, and then
        appending args to it. """
        cmd = [ ]
        cmd += self._cmd
        if args is not None :
            cmd += args
        if not self._opt.execute :
            print "Not executing:", cmd
            return
        if not self._opt.quiet :
            print "Executing:", cmd
        p = Popen( cmd, stdout=PIPE )
        for i in p.stdout :
            print >>self._ofile, i.rstrip( )
        p.wait( )

    def RunLoop( self, path, fixed_args, arg_prefix, fn ) :
        """ Run the cli multiple times in a loop.
        For the passed in path, this function reads the file; for each line in
        the file, it invokes the cli with the text from that line a command
        line argument, after passing the text through the passed in function
        (which returns the actual text / list of arguments to append to the
        command line)."""
        try :
            fh = open( path, "r" )
            for line in fh :
                args = copy.copy(fixed_args)
                value = fn(line)
                if value is None :
                    continue
                if type(value) == list or type(value) == tuple:
                    args += value
                elif arg_prefix is not None :
                    args.append(arg_prefix+": "+value)
                else :
                    args.append(value)
                self.RunCli( args )
        except IOError as e :
            print >>sys.stderr, e
            sys.exit(1)

    def HostLookup( self, host ) :
        """ Lookup a host.  If the passed in host looks like an IP address,
        return that string.  If not, attempts to lookup the string as a host
        name, and the matching IP address.  If the lookup fails, returns
        None. """
        host = host.strip()
        if re.match( r'\d+\.', host ) :
            return host
        try :
            return socket.gethostbyname(host)
        except Exception as e:
            print >>sys.stderr, "Failed to lookup host", host, e
            return None
        
    def Init( self ) :
        """ Initialize everything """
        self.InitParser( )
        self.Parse( )
        self.InitCommand( )

    def Main( self ) :
        """ Main execution """
        if self._opt.out is not None :
            self._ofile = open( self._opt.out, "w" )
        else :
            self._ofile = sys.stdout

        if self._opt.agent_file is not None :
            args = ["--request-header"]
            self.RunLoop( self._opt.agent_file, args,
                          "User-Agent", lambda s:s.strip() )
        elif self._opt.rip_file is not None :
            args = ["--remote-ip"]
            self.RunLoop( self._opt.rip_file, args, None, self.HostLookup )
        else :
            self.Run( )


main = Main( )
main.Init( )
main.Main( )

### Local Variables: ***
### py-indent-offset:4 ***
### python-indent:4 ***
### python-continuation-offset:4 ***
### tab-width:4  ***
### End: ***
