== How Data is Exposed

TBD: Perhaps pull out persistence to an advanced topic in a separate chapter?

IronBee exposes data in two forms. Data can be in defined as a var or as a stream. Vars are used for relatively small amounts of data where the entire value can be stored. Streams are used for large amounts of data (or data with an unknown length), such as request and response bodies. Streams are delivered in chunks and as such may not have the entire value at once, which limits how a stream can be inspected.

In addition to inspection, vars are the primary means of exposing and exchanging data between rules and modules. Vars can be used to store state during a transaction as well as configuration of policies and rulesets. A full list of the defined data vars is in <<_module_reference>>, however IronBee allows for the creation and modification of arbitrary vars. New variable vars can be defined, initialized in various ways within the IronBee configuration as well as in rules and modules. This section discusses defining and initializing rules via the configuration, leaving further discussion for the Rules section.

Vars are defined and initialized in the the configuration through two primary directives.  The scope of these variables is confined to the configuration context.  Variables can be defined in the main (global) scope, within a site scope or within a location scope based on where the directives are used in the configuration.

=== Defining and Initializing Scalar Variables

A simple scalar variable is both defined and initialized with the `InitVar` directive.

----
InitVar MY_VAR "my value"
----

The variable will then be available as a normal field to all rules and modules active in the same configuration context (scope). See the full documentation for the <<_initvar>> directive for more details.

=== Defining and Initializing Collections

Similar to the `InitVar` directive, you can also define and initialize collections with the `InitCollection` directive.

----
InitCollection MY_COLLECTION
----

The above will define an empty `MY_COLLECTION` collection. To both define and initialize a collection, you can utilize a number of additional `InitCollection` features. The most basic form allows specifying key/value pairs with the collection.

----
InitCollection MY_COLLECTION vars: \
    key1=value1 \
    key2=value2 \
    key3=value3
----

In addition to initializing the key values within the configuration file, you may also initialize the collection via an external JSON formatted file, allowing for controlling the data defining the collection outside of the IronBee configuration.

----
InitCollection MY_COLLECTION json-file:///path/to/persisted/data/mycollection.json
----

The JSON is formatted as simple name/value pairs.

[source,json]
.Example JSON:
----
{
    "key1": "value1",
    "key2": "value2",
    "key3": "value3"
}
----

=== Persisting Collections

In addition to defining and initializing collections with static data, IronBee also allows for persisting collections which have been manipulated in IronBee. This is accomplished in a few different ways, depending on your needs. If you need to persist a single instance of a collection, then you can just add the `persist` option to the `InitCollection` directive.

----
InitCollection MY_COLLECTION json-file:///path/to/persisted/data/mycollection.json persist
----

With the addition of the `persist` option, any data within the collection will be written out to the JSON file at the end of the transaction. The next transaction will then be initialized with the manipulated data.  Often, though, you do not want to share the same collection for all transactions. Instead you need to be able to save different instances of the collection based on some other field or set of fields as a key. To do this, you need to load the persistence framework and the persist module to gain some additional functionality.

.Load the persistence framework and module.
----
LoadModule ibmod_persistence_framework.so
LoadModule ibmod_persist.so
----

The persist module uses the persistence framework to allow for some more advanced persistence, such as providing multiple instances of persisted collections as well as expiration.

.The persistence filesystem URI.
----
persist-fs:///path/to/persisted/data [key=VALUE] [expire=SECONDS]
----

The `persist-fs` URI allows specifying a path to store persisted data.  The `key` parameter specifies a value to identify an instance of the collection. The `key` value can be any text or a field expansion (e.g., `%{MY_VAR_NAME}`). The `expire` parameter allows setting the expiration of the data stored in the collection in seconds. On initialization, the collection is populated from the persisted data. If the data is expired when the collection is initialized, it is discarded and an empty collection will be created.

.Define a persistence store.
----
PersistenceStore MY_STORE persist-fs:///path/to/persisted/data
----

Once one or more persistence stores are defined, you can then map a a collection to the store, setting various options. The mapping can be a single instance (such as with `InitCollection`) or it can be based on a specific key, such as `REMOTE_ADDR`. The persisted data can also have an expiration.

With a global collection, you just map a collection name to a persistence store name. This is similar to using `InitCollection` with the `persist` option, but using a defined store instead of a specific file.

.Global Collection:
----
PersistenceMap MY_COLLECTION MY_STORE
PersistenceMap MY_EXPIRE_COLLECTION MY_STORE expire=300
----

To store an instance of a collection, you just need to add the `key` parameter to the mapping. For example, to store an instance of the collection based on the IP address or session ID you would specify the key via variable expansion.

----
PersistenceMap IP_DATA MY_STORE key=%{REMOTE_ADDR}
PersistenceMap SESS_DATA MY_STORE key=%{REQUEST_COOKIES:jsessionid}
----

Any data contained in these collections will be read from a file based on the key and stored in the named collection. At the end of the transaction, the data is written out to the same file. Since this data may accumulated, you will probably want to specify an expiration.  This is done by using the `expire` option, which takes an expiration time in seconds. If more than the number of seconds elapses between the collection being written out and read back in, the data is purged and the collection will be empty. This can be used to store state for a given time period across transaction boundaries.

.A more complete example of IP based blocking.
----
# Load persistence modules
LoadModule ibmod_persistence_framework.so
LoadModule ibmod_persist.so

...

# Define a persistence store
PersistenceStore MY_STORE persist-fs:///path/to/persisted/data

...

# Initialize a collection from the persistence store keyed off of REMOTE_ADDR.
# The IP collection is now associated with the REMOTE_ADDR and any updates
# will be persisted back to the persistence store with the REMOTE_ADDR key.
# Different instances of the IP collection are stored based on the key. The
# data stored in this collection will expire 300 seconds after persisted.
PersistenceMap IP MY_STORE key=%{REMOTE_ADDR} expire=300

# Check a value from the persisted collection to determine if a block should
# occur. If the IP block is in effect, then processing stops here with an
# immediate block.
Rule IP:block @gt 0 id:persist/isblocked phase:REQUEST_HEADER event block:immediate

# Perform some checks, setting block flag.
# NOTE: None of these will execute if an IP based block is in effect via the rule
# above.
Rule ... block

# Update the persistent IP collection. This will store a block=1 parameter
# for the IP collection associated with the REMOTE_ADDR key if any rule has issued
# an advisory block. If the IP collection is pulled from the store again
# (within the expiration), then the rule above will immediatly block the transaction.
Rule FLAGS:block @ne 0 id:persist/setblock phase:REQUEST event block:immediate setvar:IP:block=1

# After the transaction completes, the modified values are persisted and the
# persisted IP:block=1 will be used to block all transactions from the same IP
# address for the next 300 seconds.
----

Since the data is only purged when it is attempted to be read back in
after expiring, the data may still accumulate on the filesystem. It may
be required to run a periodic cleanup process to purge any expired
files. In the future IronBee will provide a utility for this, but for
now the expiration date is encoded in the filename.

----
# Format: uuid/expiration-tempname
0de114da-8ada-55ad-a6de-e68a1263412a/001364624257-0004d91e578bc99f.json.dXFR9d
----

Periodic purging could be accomplished with a cron job to check that the
current epoch based date is greater than that encoded in the file.

----
#!/bin/sh

# Specify the persist-fs: base directory
PERSIST_FS_BASEDIR="/tmp/ironbee/persist/fs"

# Current epoch based date
DSTAMP=`date "+%s"`

# Iterate through files
for file in `find $PERSIST_FS_BASEDIR -type f -name '*.json.*'`; do
    # Extract the epoch based expiration from the filename
    expires=`echo $file | sed 's%.*/0*\([0-9]*\)-.*%\1%'`

    # Check if the expires was extracted and the current date
    # is greater than the expiration, removing the file.
    if [ -n "$expires" -a "$DSTAMP" -gt "$expires" ]; then
        echo "PURGE: $file expired=`date -j -r $expires`"
        rm $file
    fi
done
----

