== IronBee Diagnostics and Developer Tools

IronBee comes with a number of tools for diagnostics and development of both modules and rules.

=== Rule Engine Logging and Diagnostics

IronBee has a separate logging facility for rule engine which is meant to make rule diagnostics easier. Rule engine logging is controlled through two directives. There is also a variable that can be set to enable internal tracing of the rule execution engine, which is generally only useful for developers.

Typically rule execution logging is enabled as follows:

----
### Rule Engine Logging
# Control what data is logged
RuleEngineLogData default
# Control at which log level data is logged
RuleEngineLogLevel info
----

Full logging, which will generate a lot of data, can be enabled by setting `RuleEngineLogData` to `all`, however there is quite a bit of control over what is logged. See the `RuleEngineLogData` in the ? documentation for details. An example of full rule engine logging is below.

----
### Rule Engine Logging
RuleEngineLogData all
RuleEngineLogLevel info

### Match "dirty" or "attack" in the request
Rule REQUEST_URI REQUET_HEADERS ARGS @rx "dirty|attack" \
    id:test/1 phase:REQUEST \
    severity:60 confidence:50 \
    "msg:Matched %{CAPTURE:0}" \
    capture \
    event block

### Perform an actual block action at the end of the phase
### if marked to block
Rule FLAGS:block.count() @gt 0 \
    id:block/1 phase:REQUEST \
    "msg:Blocking request" \
    status:403 \
    block:phase
----

The above will produce rule engine logging similar to below.

----
[] PHASE REQUEST_HEADER_STREAM 
[] TX_START 1.2.3.4:52980 waf-test.example.com
[] REQ_LINE GET /?a=1&b=dirty&c=attack&d=4 HTTP/1.1
[] REQ_HEADER Host: waf-test.example.com
[] REQ_HEADER User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:18.0) Gecko/20100101 Firefox/18.0
[] REQ_HEADER Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
[] REQ_HEADER Accept-Language: en-US,en;q=0.5
[] REQ_HEADER Connection: keep-alive
[] PHASE REQUEST_HEADER      
[] PHASE REQUEST
[rule:"site/.../test/1" rev:1] RULE_START PHASE
[rule:"site/.../test/1" rev:1] TARGET "REQUEST_URI" BYTESTR "request_uri" "\/?a=1&b=dirty&c=attack&d=4"[rule:"site/.../test/1" rev:1] OP rx("dirty|attack") TRUE
[rule:"site/.../test/1" rev:1] ACTION event("") 
[rule:"site/.../test/1" rev:1] ACTION block("") 
[rule:"site/.../test/1" rev:1] EVENT site/.../test/1 Observation Block [50/60] [] "Matched dirty" 
[rule:"site/.../test/1" rev:1] TARGET REQUET_HEADERS NOT_FOUND[rule:"site/.../test/1" rev:1] TARGET "ARGS" BYTESTR "ARGS:a" "1"
[rule:"site/.../test/1" rev:1] OP rx("dirty|attack") FALSE
[rule:"site/.../test/1" rev:1] TARGET "ARGS" BYTESTR "ARGS:b" "dirty"
[rule:"site/.../test/1" rev:1] OP rx("dirty|attack") TRUE
[rule:"site/.../test/1" rev:1] ACTION event("") 
[rule:"site/.../test/1" rev:1] ACTION block("") 
[rule:"site/.../test/1" rev:1] EVENT site/.../test/1 Observation Block [50/60] [] "Matched dirty" 
[rule:"site/.../test/1" rev:1] TARGET "ARGS" BYTESTR "ARGS:c" "attack" 
[rule:"site/.../test/1" rev:1] OP rx("dirty|attack") TRUE[rule:"site/.../test/1" rev:1] ACTION event("") 
[rule:"site/.../test/1" rev:1] ACTION block("") 
[rule:"site/.../test/1" rev:1] EVENT site/.../test/1 Observation Block [50/60] [] "Matched attack"
[rule:"site/.../test/1" rev:1] TARGET "ARGS" BYTESTR "ARGS:d" "4"
[rule:"site/.../test/1" rev:1] OP rx("dirty|attack") FALSE
[rule:"site/.../test/1" rev:1] RULE_END[rule:"site/.../block/1" rev:1] RULE_START PHASE
[rule:"site/.../block/1" rev:1] TFN count() LIST "FLAGS" 1 
[rule:"site/.../block/1" rev:1] TARGET "FLAGS:block.count()" NUM "FLAGS:FLAGS" 1
[rule:"site/.../block/1" rev:1] OP gt(0) TRUE
[rule:"site/.../block/1" rev:1] ACTION status(403) 
[rule:"site/.../block/1" rev:1] ACTION block("phase") 
[rule:"site/.../block/1" rev:1] RULE_END
[] PHASE RESPONSE_HEADER_STREAM
[] RES_LINE HTTP/1.1 403 Forbidden
[] RES_HEADER Date: Fri, 22 Mar 2013 15:36:27 GMT
[] RES_HEADER Connection: close
[] RES_HEADER Server: ATS/3.2.2
[] PHASE RESPONSE_HEADER     
[] PHASE RESPONSE_BODY_STREAM
[] PHASE POST_PROCESS
[] PHASE LOGGING
[] AUDIT /var/log/ironbee/events/118d9ea6-933d-400e-b980-cdad773dceee_9e8d34a4-1431-4a90-a79a-de9fe88fb111.log
[] TX_END
----

For a production system, something like this may be suitable, which will only log events that are generated and audit log files that are written:

----
### Log only events and audit log information
RuleEngineLogData event audit
RuleEngineLogLevel notice
----

If you need further tracing through rule execution, then you can set the rule engine debug log level. This will potentially log a lot of data, but will allow for debugging issues that may not be exposed by the normal rule engine logging facility. The following will enable full trace mode in the rule engine:

----
Set RuleEngineDebugLogLevel trace
----

=== Command Line Tool (clipp)

IronBee includes a full featured command line tool named `clipp` (pronounced clippy) that can be used to run transactions through IronBee from various data sources such as its own native protobuf format, raw HTTP files, pcap network captures, audit logs and others. Clipp can also translate between the various formats. The interface to clipp was inspired by the brilliant socat utility (http://www.dest-unreach.org/socat/). Clipp is best explained through examples, but in general, clipp take one or more inputs, optional modifiers and a single consumer. The input data passes through modifiers into the consumer.

The following will take `raw` HTTP input files (`request.http` and `response.http`), instantiate an `ironbee` consumer with the specified configuration (`ironbee.conf`) and then push the data through the IronBee engine in the same way IronBee embedded in a webserver or proxy. Using clipp, you can test IronBee configuration files prior to moving them to a webserver or proxy. With clipp, if you specified a LogFile in the configuration, then the logs will go there, otherwise it will go to stderr.

----
$ clipp raw:request.http,response.http ironbee:ironbee.conf
----

Multiple transactions are also supported, including in multiple formats:

----
$ clipp \
raw:request1.http,response1.http \
raw:request2.http,response2.http \
ironbee:ironbee.conf
----

Modifiers are also supported, such as changing the IP/port used:

----
$ clipp \
raw:request1.http,response1.http \
@set_local_ip:1.2.3.4 \
@set_local_port:8080 \
raw:request2.http,response2.http \
@set_local_ip:5.6.7.8 \
@set_local_port:80 \
ironbee:ironbee.conf
----

With many parameters, the command line can get tedious, so clipp also supports a configuration file format:

----
### clipp.conf

# Transaction 1
raw:request1.http,response1.http
  @set_local_ip:1.2.3.4
  @set_local_port:8080

# Transaction 2
raw:request2.http,response2.http
  @set_local_ip:5.6.7.8
  @set_local_port:80

# IronBee Consumer
ironbee:ironbee.conf
----

----
$ clipp -c clipp.conf
----

Clipp's native protobuf format can encapsulate all input, including modifiers, into a single compact format. This format is produced by using the writepb consumer:

----
$ clipp \
raw:request1.http,response1.http \
raw:request2.http,response2.http \
writepb:input.pb
----

Full documentation on clipp is in Markdown format in the source tree: https://github.com/ironbee/ironbee/blob/master/clipp/clipp.md

=== Developer Modules

IronBee includes some developer modules that contain some diagnostic features. One that can aide in diagnosing inspection issues is the `TxDump` directive. This directive allows for dumping some internal IronBee state to a log file. To use `TxDump`, you need to load the `txdump` module.

----
LoadModule "ibmod_txdump.so"
----

Once this is done, you can use the `TxDump` directive to log data to a file.

----
TxDump TxFinished file:///tmp/ironbee_diag.log All
----

And you will get something like the following.

----
[TX 6bcb584c-7f84-461a-93b4-d576e7fd72a7 @ tx_finished_event]
  Started = 2013-04-25T17:34:00.2508-0700
  Hostname = waf-test.example.com
  Effective IP = 5.6.7.8
  Path = /
  Context
    Name = any:location:/
    Site name = any
    Site ID = 0CA1665C-F27F-4763-A3E0-A31A00477497
    Location path = /
  Connection
    Created = 2013-04-25T17:34:00.2508-0700
    Remote = 5.6.7.8:80
    Local = 1.2.3.4:1234
    Context
      Name = main:site:any
      Site name = any
      Site ID = 0CA1665C-F27F-4763-A3E0-A31A00477497
  Request line:
    Raw = "GET /path/test?foo=bar HTTP/1.1"
    Method = "GET"
    URI = "/path/test?foo=bar"
    Protocol = "HTTP/1.1"
  Request Header
    Host = "waf-test.example.com"
    User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:18.0) Gecko/..."
    Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    Accept-Language = "en-US,en;q=0.5"
    Connection = "keep-alive"
  Response line:
    Raw = "HTTP/1.1 301 Moved Permanently"
    Protocol = "HTTP/1.1"
    Status = "301"
    Message = "Moved Permanently"
  Response Header
    Location = "http://www.example.com/"
    Content-Type = "text/html; charset=UTF-8"
    Date = "Wed, 26 Oct 2012 02:36:41 GMT"
    Expires = "Fri, 25 Nov 2012 02:36:41 GMT"
    Cache-Control = "public, max-age=2592000"
    Server = "Apache"
    Content-Length = "219"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
  Flags = 0380beb8
    00000001 "Error" = Off
    00000002 "HTTP/0.9" = Off
    00000004 "Pipelined" = Off
    00000008 "Request Started" = On
    00000020 "Seen Request Header" = On
    00000040 "No Request Body" = Off
    00000080 "Seen Request Body" = On
    00000100 "Seen Request Trailer" = Off
    00000200 "Request Finished" = On
    00000400 "Response Started" = On
    00001000 "Seen Response Header" = On
    00002000 "Seen Response Body" = On
    00004000 "Seen Response Trailer" = Off
    00008000 "Response Finished" = On
    00010000 "Suspicious" = Off
    00020000 "Block: Advisory" = Off
    00040000 "Block: Phase" = Off
    00080000 "Block: Immediate" = Off
    00100000 "Allow: Phase" = Off
    00200000 "Allow: Request" = Off
    00400000 "Allow: All" = Off
    00800000 "Post-Process" = On
    02000000 "Inspect Request Header" = On
    04000000 "Inspect Request Body" = Off
    08000000 "Inspect Response Header" = Off
    10000000 "Inspect Response Body" = Off
  ARGS:
    ARGS = [1]
    ARGS:foo = "bar"
  Data:
    response_line = "HTTP/1.1 301 Moved Permanently"
    request_uri = "/path/test?foo=bar"
    request_protocol = "HTTP/1.1"
    request_uri_params = [1]
      request_uri_params:foo = "bar"
    FIELD_NAME = ""
    request_content_type = ""
    request_uri_path = "/path/test"
    remote_addr = "5.6.7.8"
    request_host = ""
    request_filename = ""
    response_headers = [9]
      response_headers:Location = "http://www.example.com/"
      response_headers:Content-Type = "text/html; charset=UTF-8"
      response_headers:Date = "Wed, 26 Oct 2012 02:36:41 GMT"
      response_headers:Expires = "Fri, 25 Nov 2012 02:36:41 GMT"
      response_headers:Cache-Control = "public, max-age=2592000"
      response_headers:Server = "Apache"
      response_headers:Content-Length = "219"
      response_headers:X-XSS-Protection = "1; mode=block"
      response_headers:X-Frame-Options = "SAMEORIGIN"
    request_uri_password = ""
    request_uri_scheme = ""
    request_uri_query = "foo=bar"
    remote_port = 80
    request_line = "GET /path/test?foo=bar HTTP/1.1"
    server_addr = "1.2.3.4"
    response_status = "301"
    response_message = "Moved Permanently"
    CAPTURE = [0]
    FIELD_NAME_FULL = ""
    request_uri_username = ""
    request_body_params = [0]
    server_port = 1234
    response_cookies = [0]
    request_uri_port = ""
    response_protocol = "HTTP/1.1"
    conn_tx_count = 1
    request_uri_raw = "/path/test?foo=bar"
    CA = [0]
    auth_password = ""
    request_headers = [5]
      request_headers:Host = "waf-test.example.com"
      request_headers:User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:18.0) Gecko/20100101 Firefox/18.0"
      request_headers:Accept = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
      request_headers:Accept-Language = "en-US,en;q=0.5"
      request_headers:Connection = "keep-alive"
    request_method = "GET"
    response_content_type = ""
    request_uri_fragment = ""
    request_uri_path_raw = "/path/test"
    ARGS = [1]
      ARGS:foo = "bar"
    FLAGS = [5]
      FLAGS:suspicious = 0
      FLAGS:inspectRequestHeader = 1
      FLAGS:inspectRequestBody = 0
      FLAGS:inspectResponseHeader = 0
      FLAGS:inspectResponseBody = 0
    auth_username = ""
    auth_type = ""
    request_uri_host = ""
    request_cookies = [0]
----

What data you log can be tailored. See the documentation for the `TxDump` directive for the full syntax.

