[[module.write_clipp]]
=== Write Transactions in Clipp Format Module (write_clipp)

Allow writing out transactions to `clipp` commandline utility compatible (PB format) input files. This module is meant to be able to record transactions for diagnostics, debugging and testing purposes.

Either action must be fired before IB_PHASE_LOGGING in order to capture the current transaction.  They must be fired the body phases in order to capture the body.  Otherwise, it does not matter which phase they are fired in; non-body writing and all file I/O takes place in the logging phase.

The resulting PB is a reproduction of the traffic, not an accurate reproduction of the event stream.  Differences include a lack of timing information, a lack of multiple header/body events, and only including body up to the buffering limit.  These limitations reflect an requirement at being able to log the current transaction if a rule fires for it.  Such a requirement requires reconstructing an event sequence.  A future module may provide less control and higher fidelity.

NOTE: To get the body data, inspection must be enabled for all aspects of the transaction and buffering must be enabled. The buffering limit will limit how much of the body is written.

WARNING: These actions can have a significant performance impact in both time and space.

.Example Usage
----
LoadModule write_clipp

# Enable inspection of all of the transaction
InspectionEngineOptions all

# Enable buffering of the bodies and set limits.
RequestBuffering On
RequestBodyBufferLimit 1048576
ResponseBuffering On
ResponseBodyBufferLimit 1048576

# Default Site
<Site any>
    SiteId 7E86CAA0-4F1F-4AA5-BFE4-A17D85ADD76D
    Service *:*
    Hostname *

    # Write all connection data to a file
    Action id:record/1 phase:REQUEST_HEADER write_clipp_conn:/tmp/ib-conn-data.pb

    RuleEnable all
</Site>
----

==== Actions

[[action.write_clipp_conn]]
===== write_clipp_conn
[cols=">h,<9"]
|===============================================================================
|Description|Append a connection with the current transaction to a file in CLIPP format.
|       Type|Action
|     Syntax|`write_clipp_conn:<file>`
|Cardinality|0..1
|     Module|write_clipp
|    Version|0.11
|===============================================================================

This action will append the current connection information as well as the current transaction and all future transactions to a protobuf (PB) CLIPP formated file. The file can then be used in clipp as input.

NOTE: Var expansion is supported in the filename.

[[action.write_clipp_tx]]
===== write_clipp_tx
[cols=">h,<9"]
|===============================================================================
|Description|Append a transaction with the current transaction to a file in CLIPP format.
|       Type|Action
|     Syntax|`write_clipp_tx:<file>`
|Cardinality|0..1
|     Module|write_clipp
|    Version|0.11
|===============================================================================

This action will append the current transaction to a protobuf (PB) CLIPP formated file. The file can then be used in clipp as input.

NOTE: Var expansion is supported in the filename.

