[[module.xrules]]
=== XRules Module (xrules)

Adds support for high level rule logic for common Firewall like matching and exceptions.

==== Directives

[[directive.XRuleEventTag]]
===== XRuleEventTag
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended EventTag rule.
|		Type|Directive
|     Syntax|`XRuleEventTag <tag1> <tag2> ... <tagN> <Action>`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.10
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. For EventTags, priority is ignored.

An XRuleEventTag directive is used to setup EventTag based rules. These rules will match (potentially multiple times) if an event is generated with one of the given tag values as a prefix.  For example, you may have tags such as "SQLi" which are added by any SQLi rules that match.

.Example:
----
XRuleEventTag SQLi XSS block
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleException]]
===== XRuleException
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended Exception rule, which allows combining multiple XRules.
|		Type|Directive
|     Syntax|`XRuleException <xrule1> <xrule2> ... <xruleN> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.10
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. Exception xrules are used to AND together multiple other xrule types.

Typically to produce an exception, you need to AND together multiple XRules. For instance you may want to combine IPv4 with Path and EventTags to disable blocking.

Each `xrule` is specified as a type prefix followed by a colon and the xrule expression. For example, `Ipv4:1.2.3.4/32` or `Path:/some-path`. Each `xrule` argument must resolve true for the action to be executed.

.Example: Disable blocking for IPs in net 1.2.3.0/24 using path /admin where SQLi is found.
----
XRuleException "Ipv4:1.2.3.0/24" "Path:/admin" "EventTag:SQLi" disableBlockingMode
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleGenerateEvent]]
===== XRuleGenerateEvent
[cols=">h,<9"]
|===============================================================================
|Description|Controls if log events are generated by matching XRules.
|		Type|Directive
|     Syntax|`XRuleGenerateEvent On \| Off`
|    Default|Off
|    Context|Any
|Cardinality|0..1
|     Module|xrules
|    Version|0.10
|===============================================================================

If set to `On`, then XRules that match will produce an event. For example, an XRuleIpv4 would produce an event similar to the following regular rule actions:

.XRuleIpv4 1.2.3.4/32 Block
----
Rule REMOTE_ADDR @ipmatch 1.2.3.4/32 id:xrule/ipv4 tag:xrule/ipv4 event "msg:Ipv4 1.2.3.4/32 matched: Block"
----

[[directive.XRuleGeo]]
===== XRuleGeo
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended geo rule.
|		Type|Directive
|     Syntax|`XRuleGeo <2-char-country> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleGeo is used to setup Geo (country) based rules.

.Example:
----
XRuleGeo US scaleThreat=0.8 priority=1
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleIpv4]]
===== XRuleIpv4
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended IPv4 rule.
|		Type|Directive
|     Syntax|`XRuleIpv4 <cidr4> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleIpv4 is used to setup IPv4 based rules.

Example:
----
XRuleIpv4 192.168.0.0/16 block priority=1
----

Available Actions::
  * *priority=N* - Set rule priority.
  * *block* - Block the transaction.
  * *allow* - Allow the transaction.
  * *enableBlockingMode* - Enable blocking mode for this transaction.
  * *disableBlockingMode* - Disable blocking mode for this transaction
  * *scaleThreat=X* - Scale threat calculation (update *XRULES:SCALE_THREAT*) by floating point multiplier, X, for this transaction.
  * *enableRequestHeaderInspection* - Enable request header inspection for this transaction.
  * *disableRequestHeaderInspection* - Disable request header inspection for this transaction.
  * *enableRequestURIInspection* - Enable request URI inspection for this transaction.
  * *disableRequestURIInspection* - Disable request URI inspection for this transaction.
  * *enableRequestParamInspection* - Enable request parameter inspection for this transaction.
  * *disableRequestParamInspection* - Disable request parameter inspection for this transaction.
  * *enableRequestBodyInspection* - Enable request body inspection for this transaction.
  * *disableRequestBodyInspection* - Disable request body inspection for this transaction.
  * *enableResponseHeaderInspection* - Enable response header inspection for this transaction.
  * *disableResponseHeaderInspection* - Disable response header inspection for this transaction.
  * *enableResponseBodyInspection* - Enable response body inspection for this transaction.
  * *disableResponseBodyInspection* - Disable response body inspection for this transaction.

[[directive.XRuleIpv6]]
===== XRuleIpv6
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended IPv6 rule.
|		Type|Directive
|     Syntax|`XRuleIpv6 <cidr6> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleIpv6 is used to setup IPv6 based rules.

Example:
----
XRuleIpv6 ::1/128 block priority=1
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRulePath]]
===== XRulePath
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended path rule.
|		Type|Directive
|     Syntax|`XRulePath <path> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRulePath is used to setup URI path based rules.

Example:
----
XRulePath /admin scaleThreat=1.5 enableBlockingMode priority=1
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleRequestContentType]]
===== XRuleRequestContentType
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended request content type rule.
|		Type|Directive
|     Syntax|`XRuleRequestContentType <mime-type> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleRequestContentType is used to setup request contetnt type based rules.

Example:
----
XRuleRequestContentType application/x-www-form-urlencoded enableRequestBodyInspection
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleResponseContentType]]
===== XRuleResponseContentType
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended IPv6 rule.
|		Type|Directive
|     Syntax|`XRuleResponseContentType <mime-type> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleResponseContentType is used to setup response content type based rules.

Example:
----
XRuleResponseContentType image/png disableResponseBodyInspection
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

[[directive.XRuleTime]]
===== XRuleTime
[cols=">h,<9"]
|===============================================================================
|Description|Add an extended time rule.
|		Type|Directive
|     Syntax|`XRuleTime <time-spec> <Action> [priority=N]`
|    Default|None
|    Context|Any
|Cardinality|0..n
|     Module|xrules
|    Version|0.8
|===============================================================================

NOTE: XRules, or extended rules, are rules that implement common operations, such as Access Control Lists (ACLs). These extended rules hide much of the complexities of normal rules so that these common operations are easier to use. The priority allows conflicts to be resolved - higher priority (lower numerical value) rules will override lower priority rules.

An XRuleTime is used to setup date/time based rules.

The time-spec is in the format: `[!]DOW(,DOW)*@HH:MM-HH:MM[-|+]ZZZZ`:

* *!* - Invert rule.
* *DOW* - Day of Week (0=Sunday - 6=Saturday).
* *HH* - Two digit hour (24-hr format).
* *MM* - Two digit minute.
* *[-|+]ZZZZ* - Timezone offset from GMT

Example:
----
XRuleTime !1,2,3,4,5@08:00-17:00-0500 scaleThreat=1.5 enableBlockingMode
----

For available actions, see <<directive.XRuleIpv4,XRuleIpv4>>.

