[[module.ee]]
=== EE

==== Directives

[[directive.LoadEudoxus]]
===== LoadEudoxus
[cols=">h,<9"]
|===============================================================================
|Description|Loads an external Eudoxus Automata into IronBee.
|		Type|Directive
|     Syntax|`LoadEudoxus <name> <automata-file>`
|    Default|None
|    Context|Main
|Cardinality|0..n
|     Module|ee
|    Version|0.7
|===============================================================================

This directive will load an external eudoxus automata from `file` into the engine with the given `name`. Once loaded, the automata can then be used with the associated eudoxus rule operators such as the `ee` or `ee_match` operator.

The eudoxus automata is a precompiled and optimized automata generated by the ac_generator and ec commands in the `automata/bin` directory.  Currently, as of IronBee 0.7, a modified Aho-Corasick algorithm is implemented which can handle very large external dictionaries. Refer to the https://www.ironbee.com/docs/devexternal/ironautomata.html[IronAutomata Documentation] for more information.

==== Operators

[[operator.ee]]
===== ee
[cols=">h,<9"]
|===============================================================================
|Description|Returns true if the target matches any value in the named eudoxus automata.
|		Type|Operator
|     Syntax|`ee <named-automata>`
|      Types|String
|     Module|ee
|    Version|0.7
|===============================================================================

The `ee` operator is the "Eudoxus Executor". If the target matches any pattern in the named Eudoxus automata, then the operator returns true. The named eudoxus automata must first be loaded with the the <<directive.LoadEudoxus,LoadEudoxus>> directive.

See also <<operator.ee_match,ee_match>> which is similar, but must match the entire target.

[[operator.ee_match]]
===== ee_match
[cols=">h,<9"]
|===============================================================================
|Description|Returns true if the target fully matches any value in the named eudoxus automata.
|		Type|Operator
|     Syntax|`ee_match <named-automata>`
|      Types|String
|     Module|ee
|    Version|0.7
|===============================================================================

Similar to <<operator.match,match>> and <<operator.ee,ee>>, the operator returns true if the target fully matches (pattern anchored start to end) in the named eudoxus automata.
