[[module.ee]]
=== Eudoxus Executor Module (ee)

IronBee has a framework (IronAutomata) for defining, compiling and optimizing automata. There are a number of different automata based algorithms defined with the framework, such as a modified Aho-Corasick algorithm (ac_generator) and a trie (trie_generator). Automata for these algorithms can be generated, compiled, optimized and packed into a common execution engine named Eudoxus. As the execution engine is common to all algorithms, the Eudoxus Executor (ee) can execute the automata to perform matches using the algorithm chosen at automata generation time.

What this means is that a large data set can be packed into the Eudoxus format and then distributed. This module defines an operator to execute the packed automata in an efficient manner. One caveats of this is that the automata must be built outside IronBee with the automata generator utilities provided. instead of being built at IronBee config time.

TODO: Point to Automata docs.

This module allows loading external Eudoxus Automata as well as performing matches using them.

.Example Usage
----
LoadModule ee
...
LoadEudoxus spam spamwords.ee
...
Rule ARGS @ee spam id:test/1 phase:REQUEST "msg:Found spam word (%{CAPTURE:0})" event:alert capture
----

==== Directives

[[directive.LoadEudoxus]]
===== LoadEudoxus
[cols=">h,<9"]
|===============================================================================
|Description|Loads an external Eudoxus Automata into IronBee.
|		Type|Directive
|     Syntax|`LoadEudoxus <name> <automata-file>`
|    Default|None
|    Context|Main
|Cardinality|0..n
|     Module|ee
|    Version|0.7
|===============================================================================

This directive will load an external eudoxus automata from `file` into the engine with the given `name`. Once loaded, the automata can then be used with the associated eudoxus rule operators such as the `ee` or `ee_match` operator.

The eudoxus automata is a precompiled and optimized automata generated by the ac_generator and ec commands in the `automata/bin` directory.  Currently, as of IronBee 0.7, a modified Aho-Corasick algorithm is implemented which can handle very large external dictionaries. Refer to the https://www.ironbee.com/docs/devexternal/ironautomata.html[IronAutomata Documentation] for more information.

==== Operators

[[operator.ee]]
===== ee
[cols=">h,<9"]
|===============================================================================
|Description|Returns true if the target matches any value in the named eudoxus automata.
|		Type|Operator
|     Syntax|`ee <named-automata>`
|      Types|String
|    Capture|Matched text as 0.
|     Module|ee
|    Version|0.7
|===============================================================================

The `ee` operator is the "Eudoxus Executor". If the target matches any pattern in the named Eudoxus automata, then the operator returns true. The named eudoxus automata must first be loaded with the the <<directive.LoadEudoxus,LoadEudoxus>> directive.

See also <<operator.ee_match,ee_match>> which is similar, but must match the entire target.

[[operator.ee_match]]
===== ee_match
[cols=">h,<9"]
|===============================================================================
|Description|Returns true if the target fully matches any value in the named eudoxus automata.
|		Type|Operator
|     Syntax|`ee_match <named-automata>`
|      Types|String
|    Capture|Matched text as 0.
|     Module|ee
|    Version|0.7
|===============================================================================

Similar to <<operator.match,match>> and <<operator.ee,ee>>, the operator returns true if the target fully matches (pattern anchored start to end) in the named eudoxus automata.
