#!/usr/bin/env ruby

require '../../clipp/clipp_test'

require 'tc_persistence'
require 'tc_libinjection'
require 'tc_fast'
require 'tc_parser_suite'
require 'tc_modps'
require 'tc_xrules'
require 'tc_init_collection'
require 'tc_trusted_proxy'
require 'tc_txlog'
require 'tc_ee'
require 'tc_pcre'
require 'tc_abort'
require 'tc_constant'
require 'tc_write_clipp'
require 'tc_stringset'
require 'tc_header_order'
require 'tc_sqltfn'
require 'tc_block'
